dist: trusty
language: java
jdk: oraclejdk8
branches:
  only:
    - master
    - develop
    - develop-carlos-sprint4

services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS petclinic;'
  
script: mvn test -Dspring.profiles.active=mysql-travis

