dist: trusty
language: java
jdk: oraclejdk8
branches:
  only:
    - master
    - develop
    - develop-carlos-sprint4

services:
  - mysql
  
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE IF NOT EXISTS petclinic;'
  
script: 
  ./mvnw test -Dspring.profiles.active=mysql-travis

