dist: trusty
language: java
jdk: oraclejdk8
branches:
  only:
    - master
    - develop

services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE petclinic;'

script: ./mvnw test -Dspring.profiles.active=mysql
